IF (ERRCHK2(ERR_UNKNOWN, __LINE__, __LINE__, IBUB)) GOTO 999 __FILE__


__FILE__ IF (ERRCHK2(ERR_UNKNOWN, __LINE__, __LINE__, IBUB)) GOTO 999 __FILE__


 IF (ERRCHK2(ERR_UNKNOWN, __LINE__, __LINE__, IBUB)) GOTO 999 __FILE__ __FILE__ this